### ISSUE TITLE
CORS alternative

### ISSUE THREAD

**Issue by Immortalin** [gurov/stupid-rss-reader#8]
Hi! Thanks for building this. Are there any other way of dealing with CORS other than using a 3rd party proxy?

**Comment by gurov** [comment]
The second way (that I know) is using [CSP](https://en.wikipedia.org/wiki/Content_Security_Policy).
But it has pitfalls:
1) We should include all possible RSS feeds to CSP in `index.html`:
```
  <meta http-equiv="Content-Security-Policy" content="
    default-src 'self' 'unsafe-inline' 'unsafe-eval' https: https://example.com/rss 
  ">
```
2) The server must allow CORS requests to it.

**Comment by gurov** [comment]
@Immortalin In the version 4 I switched the app to use rss2json.com instead CORS proxy. Because a lot of CORS proxy very unstable
