### ISSUE TITLE
Feed urls should not get lower-cased when added

### ISSUE THREAD

**Issue by ghost** [gurov/stupid-rss-reader#9]
This is happening with Youtube RSS urls (case sensitive), leading to 404s.

**Comment by gurov** [comment]
Thx! I'll fix it

**Comment by gurov** [comment]
@dehosing the bug has been fixed, but I need some time for investigation youtube feeds. Update isn't correct.

**Comment by gurov** [comment]
Youtube RSS now works correctly. FIxed
